### PR TITLE
Fix hiding of spoiler checkbox when "Remove Controls" is enabled.

### PR DESCRIPTION
**Pull request by ccd0**
Also simplify the "Remove Controls" CSS.

This also fixes the hiding of the spoiler checkbox in the dump list,
which was happening before 4chan X v1.10.3 but I am assuming was
unintentional.

### CODE REVIEW

**Comment by nebukazar** [comment]
I have it like that because of the vertical tabbed QR. If you remove `.move` completely you can't hover anything to show the QR.

loadletter's QR seems broken again, I'll look into this.

**Comment by ccd0** [comment]
> I have it like that because of the vertical tabbed QR. If you remove .move completely you can't hover anything to show the QR.

How about `:root.qr-controls #qr > .move > *` then?

**Comment by nebukazar** [comment]
Should do the trick.

**Comment by nebukazar** [comment]
Actually never mind that, I'm going to keep the `Quick Reply` label, everything else will be hidden. It's better than having this little thing you can barely see.

**Pull request merged**
